### PR TITLE
Changes to move_check

### PR DESCRIPTION
**Pull request by Fredster64**
Hello, I've been watching your chess program for a couple of days, and I have had a few ideas for potential changes that could be made. One of these ideas, which I have started work on in this branch, is a change to the check_moves function. 
Instead of implementing it via inheritance, I've opted to use the Strategy pattern - I've created a MoveCheckInterface that each piece refers to to get its movement. Now, all of the code from the piece-specific overrides of check_moves has been moved to the MoveCheckInterface. Not only have I managed to save about 100 lines of code from the previous implementation, but I think that this interface is easier to adapt and maintain. 
That said, the changes I've made in the branch are by no means complete - I haven't done much in way of error checking or optimisation. Instead, I've given you a rough outline of how the interface would work so that you can decide whether or not you want to incorporate it in the project before I get into the specifics of debugging etc.. 
On a side note, I'm new to GitHub, so if I've gone about this the wrong way then don't be afraid to say so!

### CODE REVIEW

**Comment by sachin3796** [comment]
Hi! Thanks for submitting a pull request to my project, I'm really happy that you have decided to help me with my personal project! I have unfortunately just updated the previous implementation with a new function, so there are now merge conflicts.

I'm going to open a new branch, and try to resolve any merge requests before pushing back into Master.

Thanks again for your help, and for my first ever fork and pull request. :)

**Comment by Fredster64** [comment]
Glad I could help! :) 
If you need to ask anything more about the MCI then don't hesitate to let me know. In the meantime, I'm happy to keep an eye on the project and let you know if I find anything else that might help, if that's okay with you?

**Comment by sachin3796** [comment]
Hi! I have recently pushed the implementation to my branch, withImplementation. If you want to, please let me know if this is what you were suggesting with your improvement, it is compiling on my side and is working in the same manner as my current Master branch.

Thanks for the suggestion, feel free to suggest anything else if you would like.

**Comment by Fredster64** [comment]
Looks great! I'll keep an eye out if I notice anything. 

It looks to me like the next step is trying to sort out the 'check' mechanics - I might play around with trying to implement that in my fork.

**Pull request merged**
